// react-app/src/components/About.tsx
import React from 'react';
import './About.css';

const About: React.FC = () => {
  const stats = [
    { label: 'Years in Business', value: '10+' },
    { label: 'Happy Customers', value: '5000+' },
    { label: 'Team Members', value: '150+' },
    { label: 'Projects Completed', value: '2000+' }
  ];

  return (
    <section className="about" id="about">
      <h2>About Us</h2>
      <p>We are a leading technology company dedicated to providing innovative solutions that empower businesses worldwide. Our team of experts brings over 10 years of experience in cloud infrastructure, security, and digital transformation. We believe in delivering excellence through cutting-edge technology and exceptional customer service.</p>

      <div className="stats-container">
        {stats.map((stat, index) => (
          <div className="stat" key={index}>
            <h3>{stat.value}</h3>
            <p>{stat.label}</p>
          </div>
        ))}
      </div>
    </section>
  );
};

export default About;

// src/app/components/about/about.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css'],
  standalone: true,
  imports: [CommonModule]
})
export class AboutComponent {
  stats = [
    { label: 'Years in Business', value: '10+' },
    { label: 'Happy Customers', value: '5000+' },
    { label: 'Team Members', value: '150+' },
    { label: 'Projects Completed', value: '2000+' }
  ];
}

<section class="about" id="about">
  <h2>About Us</h2>
  <p>We are a leading technology company dedicated to providing innovative solutions that empower businesses worldwide. Our team of experts brings over 10 years of experience in cloud infrastructure, security, and digital transformation. We believe in delivering excellence through cutting-edge technology and exceptional customer service.</p>
  
  <div class="stats-container">
    <div class="stat" *ngFor="let stat of stats">
      <h3>{{ stat.value }}</h3>
      <p>{{ stat.label }}</p>
    </div>
  </div>
</section>
