// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css'],
  standalone: true
})
export class FooterComponent {
  currentYear = new Date().getFullYear();

  handleLinkClick(link: string) {
    alert(`${link} page coming soon!`);
  }
}

<footer class="footer">
  <p>&copy; {{ currentYear }} TechHub. All rights reserved.</p>
  <ul>
    <li><a href="javascript:void(0)" (click)="handleLinkClick('Privacy Policy')">Privacy Policy</a></li>
    <li><a href="javascript:void(0)" (click)="handleLinkClick('Terms of Service')">Terms of Service</a></li>
  </ul>
</footer>

// react-app/src/components/Footer.tsx
import React from 'react';
import './Footer.css';

const Footer: React.FC = () => {
  const currentYear = new Date().getFullYear();

  const handleLinkClick = (link: string) => {
    alert(`${link} page coming soon!`);
  };

  return (
    <footer className="footer">
      <p>&copy; {currentYear} TechHub. All rights reserved.</p>
      <ul>
        <li><a href="#" onClick={(e) => { e.preventDefault(); handleLinkClick('Privacy Policy'); }}>Privacy Policy</a></li>
        <li><a href="#" onClick={(e) => { e.preventDefault(); handleLinkClick('Terms of Service'); }}>Terms of Service</a></li>
      </ul>
    </footer>
  );
};

export default Footer;
